### ISSUE TITLE
command `spectral.traceFunction` not found

### ISSUE THREAD

**Issue by Aakarshan-369** [senecafron/Spectral-community#2]
![spectral issue](https://github.com/senecafron/Spectral-community/assets/53165427/e82b3c4a-0f74-4238-9ba8-16f2eed55b8b)

I installed it on VS Code and cursor multiple times, with a bunch of restarts too. 
I get the command not found error.
I tried this on a large Typescript codebase and a small JS one too, unfortunately the issue persists in both cases.

I'm running win10 with Spectral version `0.1.3`

**Comment by senecafron** [comment]
It seems that we're observing issues with OS other than Mac... I'm looking into this! And will add more logs!

**Comment by senecafron** [comment]
@Aakarshan-369 

If you update to the version 0.1.4, now there will be a new Spectral Logs channel in the Output (View > Output)

Would be great if you paste some logs from there here!

**Comment by senecafron** [comment]
Just pushed the latest version v0.1.6 Let's see if that fixes your problem! @Aakarshan-369

**Comment by senecafron** [comment]
Hey @Aakarshan-369 sorry for the late response! I'm currently fixing the bug for windows. It's pretty major one, but looking to ship it later tonight or tommorow!

**Comment by senecafron** [comment]
Hi @Aakarshan-369 the latest build of Spectral should have fixed the Windows bug! I'm closing this issue
